language: csharp
dist: trusty
sudo: requiredx
mono: none
dotnet: 2.1.300

addons:
  sonarcloud:
    organization: "virti-github"

jdk:
  - oraclejdk8

install:
    - dotnet tool install --global dotnet-sonarscanner
    - dotnet restore vtb.sln

before_script:
    - export PATH="$PATH:/home/travis/.dotnet/tools"

script:
  - dotnet sonarscanner begin /k:Virti_vtb /d:sonar.host.url="https://sonarcloud.io" /d:sonar.verbose=true
  - dotnet build vtb.sln
  - dotnet sonarscanner end /d:sonar.login=$SONAR_TOKEN || true

cache:
  directories:
    - "~/.nuget/packages"
    - "~/.local/share/NuGet/Cache"
    - "~/.sonar/cache"
