language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.1.300

addons:
  sonarcloud:
    organization: "virti-github"

jdk:
  - oraclejdk8

before_script:
  - dotnet restore

script:
  - dotnet build
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
